apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      schedulerName: custom-scheduler
      containers:
        - name: teastore-image
          image: descartesresearch/teastore-image
          resources:
            requests:
              cpu: "0.8"
            limits:
              cpu: "0.8"
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "teastore-registry"
