apiVersion: v1
kind: Node
metadata:
  name: small-node
  labels:
    kubernetes.io/hostname: small-node
spec:
  providerID: "clusterapi://small-node"
status:
  phase: Running
  conditions:
    - type: Ready
      status: "True"
  allocatable:
    cpu: "2"
    memory: "128G"
    pods: "120"
  capacity:
    cpu: "2"
    memory: "128G"
    pods: "120"