apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-webui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: compute-zone
                operator: In
                values:
                - europe
      schedulerName: custom-scheduler
      containers:
        - name: teastore-webui
          image: descartesresearch/teastore-webui
          resources:
            requests:
              cpu: "0.8"
            limits:
              cpu: "0.8"
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-webui"
            - name: REGISTRY_HOST
              value: "teastore-registry"
