apiVersion: apps/v1
kind: Deployment
metadata:
  name: authService
  labels:
    app: authService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authService
  template:
    metadata:
      labels:
        app: authService
    spec:
      containers:
        - name: authService
          resources:
            requests:
              cpu: "1.0"
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: personalized/name
#                    operator: In
#                    values:
#                      - Node1
