orchestrate: true
orchestrationDir: "./BasicExample/orchestration_default"
importNodes: true
networkDelays:
  enabled: true
  delayMap:
    worker-1-eu-west:
      worker-2-eu-west:
        mean: 0.319
        std: 0.129
      worker-asia-southeast1:
        mean: 296.453
        std: 0.656
      worker-southamerica-east1:
        mean: 199.707
        std: 0.601
      worker-us-central1:
        mean: 110.386
        std: 0.474
    worker-2-eu-west:
      worker-asia-southeast1:
        mean: 296.209
        std: 0.566
      worker-southamerica-east1:
        mean: 199.528
        std: 0.519
      worker-us-central1:
        mean: 110.485
        std: 0.362
    worker-asia-southeast1:
      worker-southamerica-east1:
        mean: 339.583
        std: 1.24
      worker-us-central1:
        mean: 185.847
        std: 0.594
    worker-southamerica-east1:
      worker-us-central1:
        mean: 143.903
        std: 0.191
scheduler: kube
initialSchedulingOrder:
  enabled: true
  order:
    - "dummy-asia-southeast1"
    - "dummy-eu-worker2"
    - "dummy-southamerica-east1"
    - "dummy-us-central1"
    - "teastore-db"
    - "teastore-registry"
    - "teastore-persistence"
    - "teastore-auth"
    - "teastore-image"
    - "teastore-recommender"
    - "teastore-webui"
scalingInterval: 15000
healthCheckDelay: 0