orchestrate: true
orchestrationDir: "./BasicExample/orchestration_default"
importNodes: true
networkDelays:
  enabled: true
  delayMap:
    worker-1-eu-west:
      worker-2-eu-west:
        mean: 0.000319
        std: 0.000129
      worker-asia-southeast1:
        mean: 0.296453
        std: 0.000656
      worker-southamerica-east1:
        mean: 0.199707
        std: 0.000601
      worker-us-central1:
        mean: 0.110386
        std: 0.000474
    worker-2-eu-west:
      worker-asia-southeast1:
        mean: 0.296209
        std: 0.000566
      worker-southamerica-east1:
        mean: 0.199528
        std: 0.000519
      worker-us-central1:
        mean: 0.110485
        std: 0.000362
    worker-asia-southeast1:
      worker-southamerica-east1:
        mean: 0.339583
        std: 0.00124
      worker-us-central1:
        mean: 0.185847
        std: 0.000594
    worker-southamerica-east1:
      worker-us-central1:
        mean: 0.143903
        std: 0.000191
scheduler: kube
initialSchedulingOrder:
  enabled: true
  order:
    - "dummy-asia-southeast1"
    - "dummy-eu-worker2"
    - "dummy-southamerica-east1"
    - "dummy-us-central1"
    - "teastore-db"
    - "teastore-registry"
    - "teastore-persistence"
    - "teastore-auth"
    - "teastore-image"
    - "teastore-recommender"
    - "teastore-webui"
scalingInterval: 15
healthCheckDelay: 0