apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineSet
metadata:
  name: small-set
  namespace: kube-system
  labels:
    max-cpus: "4"
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "10"
    capacity.cluster-autoscaler.kubernetes.io/memory: "128G"
    capacity.cluster-autoscaler.kubernetes.io/cpu: "4"
    capacity.cluster-autoscaler.kubernetes.io/maxPods: "120"
spec:
  replicas: 1
  selector:
    matchLabels:
      machine-set-name: small-set
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Ready
      status: "True"
