apiVersion: v1
kind: Node
metadata:
  name: test-node
spec:
  providerID: "clusterapi://test-node"
status:
  phase: Running
  conditions:
    - type: Ready
      status: True
  allocatable:
    cpu: "4"
    memory: "4"
    pods: 120
  capacity:
    cpu: "4"
    memory: "4"
    pods: 120