apiVersion: v1
kind: Node
metadata:
  name: large-node
spec:
  providerID: "clusterapi://large-node"
status:
  phase: Running
  conditions:
    - type: Ready
      status: "True"
  allocatable:
    cpu: "8"
    memory: "128G"
    pods: 120
  capacity:
    cpu: "8"
    memory: "128G"
    pods: 120