apiVersion: v1
clusters:
  - cluster:
      server: http://localhost:8000
      insecure-skip-tls-verify: true
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: kubernetes-admin
    name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
  - name: kubernetes-admin
