apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: compute-zone
                operator: In
                values:
                - europe
      schedulerName: custom-scheduler
      containers:
        - name: teastore-persistence
          image: descartesresearch/teastore-persistence
          resources:
            requests:
              cpu: "0.8"
            limits:
              cpu: "0.8"
          ports:
            - containerPort: 8080
          env:
            - name: HOST_NAME
              value: "teastore-persistence"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: DB_HOST
              value: "teastore-db"
            - name: DB_PORT
              value: "3306"
