apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-southamerica-east1
spec:
  replicas: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker-southamerica-east1
      schedulerName: custom-scheduler
      containers:
        - name: with-node-affinity
          image: registry.k8s.io/pause:2.0
          resources:
            requests:
              cpu: "100m"