apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: machine-2
  namespace: kube-system
  labels:
    machine-set-name: my-machine-set
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: MachineSet
      name: my-machine-set
spec:
  providerID: "clusterapi://node-2"
status:
  phase: Running
  nodeRef:
    apiVersion: v1
    kind: Node
    name: node-2